services:

  mysql:
    image: mysql:5.7
    container_name: login-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_DATABASE: 'TODO'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - login-network

  backend:
    image: login-backend
    container_name: login-backend
    restart: unless-stopped
    command: 'python3 -m api'
    build:
      context: ./backend
    environment:
      API_RELOAD: "true"
      API_DEBUG: "true"
    volumes:
      - ./backend/api:/code/backend/api
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - login-network

  frontend:
    image: login-frontend
    container_name: login-frontend
    restart: unless-stopped
    build:
      context: ./frontend
    volumes:
      - ./frontend:/code/frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - login-network

volumes:
  mysql_data:

networks:
  login-network:
    driver: bridge
